<?php

namespace Eighty8\LaravelSeeder\Tests\Migration;


use Eighty8\LaravelSeeder\Migration\MigratableSeeder;
use Orchestra\Testbench\TestCase;

class MigratableSeederTest extends TestCase
{
    /** @var SomeMigratableSeeder */
    private $migratableSeeder;

    /** @test */
    public function shouldGetConnection()
    {
        // Given

        // When
        $result = $this->migratableSeeder->getConnection();

        // Then
        $this->assertNull($result);
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->migratableSeeder = new SomeMigratableSeeder();
    }
}

class SomeMigratableSeeder extends MigratableSeeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        // TODO: Implement run() method.
    }

    /**
     * Reverses the database seeder.
     */
    public function down(): void
    {
        // TODO: Implement down() method.
    }
}